version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../dataset:/docker-entrypoint-initdb.d
    env_file:
      - ../.env

  app:
    build:
      context: ..
      dockerfile: .devcontainer/nodejs.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../../:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

volumes:
  postgres-data:
