version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../dataset:/docker-entrypoint-initdb.d
    env_file:
      - ../.env

  cache:
    image: redis:latest
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    env_file:
      - ../.env
    network_mode: service:db

  app:
    build:
      context: ..
      dockerfile: .devcontainer/nodejs.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../../:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

volumes:
  postgres-data:
  redis:
  redis-config:
