version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: bridge

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres-data:
